name: Auto Update Submodules

on:
  schedule:
    - cron: "0 6 * * *" # roda todo dia 6h UTC
  workflow_dispatch:     # permite acionar manualmente
  push:
    paths:
      - '.github/workflows/update-submodules.yml'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git submodule update --remote --merge
          git add .
          git commit -m "🔄 Atualiza submodules automaticamente" || echo "Nada para commitar"
          git push
